language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: ve6bJQXHBa2DQuvpe3UOrcmPZDcI/cx2eJHN9GoiAF1ax5vztqSPLJUgEJO6prFlDtZV/E0ANQG76SsP+AE1fJPin/5bwFzFT5EOTtrTBx9x6+31PztMWMmDK9QICkgme5k0WmLnlPXcnuc6rrOODniBSxXcw1+UnNOdjbPbxZ3GJS8sMnfnviKT3f6nMgfzXYrnsK6TfyW/aMnjetpuIjgDtxamp7eA6ZLUSLuOI5AWT/JP5MoZNs2/9c6s7TpzzqxoKl+P7+hqQmwcCEGsfAxgnft+96WPymEnEirZdNvKv8gO1Q38yBeIgPYvhBk5WvwtKoqBAtxtrBf2I7jL5RP0RDPk8bxL1lo13VW+Jki+T8ZwfZbM2/36yd7/yOx9iWGDPaqNJSSK0CkfyrR+n8xHC4yNp2nDnJ8xzfHcowK69Jc4iTjFHBQRwHqfkXjpWsZRKu2F2sB903Bem1k36+RQxDBkO4f6yt9yP+Jy1KZDgyeX5z9WtXmDZSpsA1Ma/vx1y9kwX4RWZvQMhxNko8gMzxfmFLTjjs7+ueFeqikxcPDxG35QQANOjkzuYEOdho9UGyDU86iqneFYtJ1wO7avkPQbv4jpN4yh9vn9w0gveOtfYexP5mtU5BeX4HkJID9ycQGARl9fpj/ssSIe9jTgdGhWuoW9EesHnjSbztA=
  # MATTERMOST_HOOK_URL
  - secure: DVjYf28rzzcjaIar5I0ZJAjj1fJpNZBWugM6oNmYD1lC9if0xyF/ccBffBgXpzi7YuvoP0kgAPTbipssPiCTz6MEhwxXbsQ3AF/0MTyb+wF3LbYLySF5imbpb/BSL3hqqFSIso8TH7sG+E82QsmmZISSHIhfSF50jrJjcDa7l5LEV0h+TPdsg8tsmHb3JPJVyuSjCtBD5HTTelOzA57g8zFC0tCB2UIERyM55cPaEl2cneM7Qr7R+bAKeDZFr3jeH1V38e60fpdS8qoESjH6mWeB8+lOB6nuR4mcUO05v9BFyd1Be7mRKMtDmlZLpkL+iA/9tH33YukX+L+nn2Yf/WskehitQ0PRpe7VlU3StBMvqPTdn6DUbi8vwnASJi/I4SHFaPmxWY9EErBPiEz/CzUQ3p6VgjOmRwlDJSRRHfeKYBvdflsT69d8U0r2Lj5wKLTHVbnLiGSPpGwbvzljhQhliBjJZv5B8OMSpIa1p764vco+MLmptVOG2fUChhWBBcvxHXC7DJHZ/jHbbsx+SqjxSiMsNgngnt84SgMXBqguAumYXFepwGByrVxRxg19UV2gHPK2e6yAIJ6FLAdW6yLBNQX8oB0rhIVbFeT8ObxmCQmaWBPayRvPFdgL4EArn8T73EsLfcdgXd1tPcXdgEjt0CC8LWV6FUtFzMrYoyk=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
